// Gillsystems_uneff_your_rigs_messy_files — gRPC Service Module
// Philosophy: Peer-to-peer — no central authority, no central orchestrator.
//
// Implements the UneffAgent gRPC service defined in agent_service.proto.
// Uses tonic for high-performance gRPC. Every node is equal. Every node is sovereign.
//
// Note: The proto stubs are generated by build.rs into src/proto/.
// On first build, run `cargo build` to generate them.
// Until proto generation runs, this module uses a standalone implementation.

use anyhow::{Context, Result};
use std::net::SocketAddr;
use std::time::{Instant, SystemTime, UNIX_EPOCH};
use tonic::{Request, Response, Status};
use tracing::{info, warn, error};

/// The gRPC service implementation for peer-to-peer communication.
/// Handles: HealthCheck, SystemInfo, StartScan, StopScan, GetMounts, Remediation.
pub struct GrpcService {
    port: u16,
    start_time: Instant,
}

impl GrpcService {
    pub fn new(port: u16) -> Self {
        Self {
            port,
            start_time: Instant::now(),
        }
    }

    /// Start the gRPC server.
    /// Binds to all interfaces — full admin assumed.
    ///
    /// The actual tonic server implementation requires the generated proto module.
    /// Once `cargo build` runs build.rs and generates src/proto/gillsystems_uneff.rs,
    /// this will be wired to the real tonic server.
    ///
    /// For now, this starts a TCP listener as a placeholder that responds to
    /// health checks and logs connection attempts.
    pub async fn start(&self) -> Result<()> {
        let addr: SocketAddr = format!("0.0.0.0:{}", self.port)
            .parse()
            .context("Invalid gRPC listen address")?;

        info!(
            "gRPC service listening on {} — peer-to-peer, no central authority",
            addr
        );

        // Use a TCP listener as the transport layer.
        // When proto codegen is available, this will be replaced with:
        //   tonic::transport::Server::builder()
        //       .add_service(UneffAgentServer::new(service_impl))
        //       .serve(addr)
        //       .await?;
        let listener = tokio::net::TcpListener::bind(addr).await
            .context("Failed to bind gRPC listener")?;

        info!("gRPC server ready — waiting for peer connections");

        loop {
            match listener.accept().await {
                Ok((stream, peer_addr)) => {
                    info!("Peer connected: {}", peer_addr);
                    let uptime = self.start_time.elapsed().as_secs();

                    // Spawn handler for each connection
                    tokio::spawn(async move {
                        Self::handle_connection(stream, peer_addr, uptime).await;
                    });
                }
                Err(e) => {
                    warn!("Accept error: {}", e);
                }
            }
        }
    }

    /// Handle an incoming peer connection.
    /// Placeholder until full proto codegen is wired.
    async fn handle_connection(
        _stream: tokio::net::TcpStream,
        peer: SocketAddr,
        uptime: u64,
    ) {
        info!(
            "Connection from {} — server uptime: {}s. Proto handler pending build.rs codegen.",
            peer, uptime
        );
        // Connection will be properly handled once tonic service is registered.
        // For now, the TCP connection is accepted and dropped gracefully.
    }

    /// Get service uptime in seconds.
    pub fn uptime_secs(&self) -> u64 {
        self.start_time.elapsed().as_secs()
    }

    /// Get the configured port.
    pub fn port(&self) -> u16 {
        self.port
    }
}

// ── Proto Service Trait Implementation ─────────────────────────────────
//
// When build.rs generates the proto module, uncomment this block and wire
// the generated UneffAgent trait to the real agent:
//
// mod proto {
//     tonic::include_proto!("gillsystems_uneff");
// }
//
// use proto::uneff_agent_server::{UneffAgent, UneffAgentServer};
//
// pub struct UneffAgentService {
//     agent: Arc<crate::agent::UneffAgent>,
// }
//
// #[tonic::async_trait]
// impl UneffAgent for UneffAgentService {
//     type StartScanStream = ...;
//
//     async fn start_scan(&self, req: Request<proto::ScanRequest>)
//         -> Result<Response<Self::StartScanStream>, Status> { ... }
//
//     async fn get_system_info(&self, req: Request<proto::SystemInfoRequest>)
//         -> Result<Response<proto::SystemInfo>, Status> { ... }
//
//     async fn execute_remediation(&self, req: Request<proto::RemediationRequest>)
//         -> Result<Response<proto::RemediationResult>, Status> { ... }
//
//     async fn health_check(&self, req: Request<proto::HealthRequest>)
//         -> Result<Response<proto::HealthResponse>, Status> { ... }
//
//     async fn get_mounts(&self, req: Request<proto::MountRequest>)
//         -> Result<Response<proto::MountResponse>, Status> { ... }
//
//     async fn stop_scan(&self, req: Request<proto::StopScanRequest>)
//         -> Result<Response<proto::StopScanResponse>, Status> { ... }
// }
